# ------------------
# BASIC APP INFO
# ------------------
spring.application.name=erp
server.port=9070
app.version=1.0.0

# Logging
logging.level.root=INFO
logging.level.com.project.erp=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# -------------------
# DATABASE CONFIG
# -------------------
#spring.datasource.url=jdbc:mysql://localhost:3306/erp
#spring.datasource.username=root
#spring.datasource.password=admin@sys
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&serverTimezone=UTC
spring.datasource.username=pS7N7QvxMbQ4CLi.root
spring.datasource.password=U3WUreE9iAQdpoJ5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# --------------------------
# HIKARI CONNECTION POOL
# --------------------------
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.max-lifetime=1800000
#datasource.hikari.connection-timeout=20000

# Optional, ensures connections are valid before use
spring.datasource.hikari.connection-test-query=SELECT 1

# --------------------------
# JPA / HIBERNATE CONFIG
# --------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ---------------------------
# THYMELEAF (if using UI)
# ---------------------------
spring.thymeleaf.cache=false

# --------------
# JWT CONFIG
# --------------
jwt.secret=mysuperlongsecretkeywithatleast32chars1234
jwt.expiration=86400000

# --------------------------
# STATIC FILES (UPLOADS)
# --------------------------
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:uploads/
spring.web.resources.cache.period=3600

# ----------------------------
# MULTIPART / FILE UPLOADS
# ----------------------------
# max size per file
spring.servlet.multipart.max-file-size=10MB
# max size per request (sum of all files)
spring.servlet.multipart.max-request-size=70MB

# ---------------------------------------
# MAIL CONFIG (use env vars in prod!)
# ---------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=geoalex1227@gmail.com
spring.mail.password=djod zujp szbi lapu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# -----------------------------
# SERVER / TIMEOUT SETTINGS
# -----------------------------
server.error.include-message=always
server.servlet.session.timeout=30m
server.tomcat.threads.max=200
server.tomcat.connection-timeout=20000